### PR TITLE
Added more Descriptions

### PR DESCRIPTION
**Pull request by Alexa-RR**

### CODE REVIEW

**Comment by Alexa-RR** [comment]
I think I might have used an older version of the file. please tell me if I am wrong 😅

**Comment by tyleo-rec** [comment]
We just went back through and updated the json massively. Unfortunately, this makes a bunch of your changes conflict with what we had. If you can resolve the conflicts, or redo the work on the latest version, we can check it in.

**Comment by tyleo-rec** [comment]
If you can't redo the changes on top, I may have a way to replay them myself but it will take me a bit longer to do this.

**Comment by Alexa-RR** [comment]
> If you can't redo the changes on top, I may have a way to replay them myself but it will take me a bit longer to do this.

That would be cool. But if you can I will happily redo it :)

**Comment by RR-Ry-Guy** [comment]
Yeah @Alexa-RR it would be best if you could redo these and we can get it update. Apologies for the trouble. Gonna close this PR out for now.

**Pull request closed without merging**
