### PR TITLE
Added Alexa’s CV2 Docs

### PR DESCRIPTION
**Pull request by Alexa-RR**

### CODE REVIEW

**Comment by Alexa-RR** [comment]
?

**Comment by tyleo-rec** [comment]
Can you resolve conflicts with this one. Happened after adding the others.

**Comment by Alexa-RR** [comment]
> Can you resolve conflicts with this one. Happened after adding the others.

Yee when I will get home I will do it

**Comment by Alexa-RR** [comment]
> Can you resolve conflicts with this one. Happened after adding the others.

There is a problem
457AC321-EFDD-45EA-8ABB-A357151A1ED0

**Comment by tyleo-rec** [comment]
You should be able to merge the conflicts yourself or maybe just close this PR and start a new one if you want this change.

**Comment by Alexa-RR** [comment]
> You should be able to merge the conflicts yourself or maybe just close this PR and start a new one if you want this change.

I am actually thinking of moving everything to cv2.pages.dev to simply my way of developing so I will close this pull request, Thanks <3

Also alexapi.cf got expired :c

**Pull request closed without merging**
