### PR TITLE
Shorted urls

### PR DESCRIPTION
**Pull request by Alexa-RR**
Since I started Working on my custom fork of this site I always had to remove the url that points to your website and change it to start with a / , this improves load times and to make my life easier, so I wanted to to merge those changes into the main repo, I have deployed a test site with these changes at https://alexa-rr.github.io/CircuitsV2Resources/ that is the same as yours, I hope you will be able to merge this pull request and going forward not using the base url in the markdown files, 

Much Love
Alexa <3

### CODE REVIEW

**Comment by Alexa-RR** [comment]
> 

it also improves load times for your website as well,

Also what do you think about making my fork the main site, I would maintain it so you wouldn't have to worry about that

**Comment by tyleo-rec** [comment]
We would not make your fork the main site even if it becomes better (and I hope it does!). However, we are always willing to take in useful changes like this. Thanks a ton!

**Comment by tyleo-rec** [comment]
So I merged this in but the site went down. I think there is an issue with the shortening. Your sample site isn't working for me either. I think you are missing the first part of the path for these.

**Comment by tyleo-rec** [comment]
In other words, I think they need to be like `/CircuitsV2Resources/designs/` rather than just `/designs/` etc.

**Comment by Alexa-RR** [comment]
> 

hmm that's weird, let me fix that

**Pull request merged**
