### PR TITLE
Fixed The shorted urls

### PR DESCRIPTION
**Pull request by Alexa-RR**
Sorry about that, I have gone ahead and fixed it, you caan try it out at https://alexa-rr.github.io/CircuitsV2Resources (if its not fixed for you refresh the page a cupule of time because its cashed)

### CODE REVIEW

**Comment by Alexa-RR** [comment]
?

**Comment by Alexa-RR** [comment]
oop?

**Comment by Alexa-RR** [comment]
?

**Comment by Alexa-RR** [comment]
Does it work for you?

**Comment by tyleo-rec** [comment]
It works but we can’t use CName on our site. I didn’t notice that the first time.

**Comment by Alexa-RR** [comment]
👀

**Comment by Alexa-RR** [comment]
Oop

**Comment by Alexa-RR** [comment]
ooooop

**Comment by Alexa-RR** [comment]
> Just back from vacation today. This still isn't working for me after clearing my browser.
> 
> image
> 
> 

Try https://alexa-rr.github.io/CircuitsV2Resources/

**Comment by Alexa-RR** [comment]
> Just back from vacation today. This still isn't working for me after clearing my browser.
> 
> image
> 
> 

Hope you had fun <3

**Comment by Alexa-RR** [comment]
@tyleo-rec have you got it working on your end?

**Comment by tyleo-rec** [comment]
Giving it another shot today.

**Pull request merged**
